# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoEuro' do
  # use_frameworks!

  # Pods for GoEuro
pod 'SDWebImage', '~> 4.0'


  target 'GoEuroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoEuroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
